---

- name: Workaround for 'ca-certificates-java' bug in Ubuntu 14 
  file:
    path: /usr/share/man/man1
    state: directory

- name: Ensure Java is installed
  apt:
    name: default-jre
    state: present
    update_cache: yes

- name: Install Zookeeper package
  apt:
    name: zookeeperd
    state: latest
    update_cache: yes
