---
- name: Include "{{ansible_os_family}}" zookeeper recipe
  include: "{{ansible_os_family}}.yml"

- name: Drop Zookeeper Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items:
    - src: "zoo.cfg.j2"
      dest: "/etc/zookeeper/conf/zoo.cfg"
      owner: "root"
      group: "root"
    - src: "myid.j2"
      dest: "/etc/zookeeper/conf/myid"
      owner: "root"
      group: "root"
    - src: "environment.j2"
      dest: "/etc/zookeeper/conf/environment"
      owner: "root"
      group: "root"
    - src: "log4j.properties.j2"
      dest: "/etc/zookeeper/conf/log4j.properties"
      owner: "root"
      group: "root"
  register: zookeeper_config

- name: Restart zookeeper
  service:
    name: "zookeeper"
    state: "restarted"
  when: zookeeper_config.changed and ansible_os_family == "Debian"

- name: Restart zookeeper
  service:
    name: "zookeeper-server"
    state: "restarted"
  when: zookeeper_config.changed and ansible_os_family == "RedHat"
