---

- name: Add java repository to ub14
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "14"

- name: Ensure Java is installed
  apt: name=openjdk-8-jre-headless state=present update_cache=yes

- name: Select java version 8 (Problems with java 9)
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- name: Check if Zookeeper is running
  command: systemctl status zookeeper
  ignore_errors: yes
  changed_when: false
  register: service_zookeeper_status

- name: Install Zookeeper when service is not found
  apt: name=zookeeperd state=latest update_cache=yes
  when: service_zookeeper_status | failed

- name: Drop Zookeeper Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items:
    - src: "zoo.cfg.j2"
      dest: "/etc/zookeeper/conf/zoo.cfg"
      owner: "root"
      group: "root"
    - src: "myid.j2"
      dest: "/etc/zookeeper/conf/myid"
      owner: "root"
      group: "root"
    - src: "environment.j2"
      dest: "/etc/zookeeper/conf/environment"
      owner: "root"
      group: "root"
    - src: "log4j.properties.j2"
      dest: "/etc/zookeeper/conf/log4j.properties"
      owner: "root"
      group: "root"
  register: zookeeper_config

- name: Restart zookeeper
  service:
    name: "zookeeper"
    state: "restarted"
  when: zookeeper_config.changed
