---
- name: Ensure Java is installed (RedHat)
  yum:
    name: java-1.8.0-openjdk-headless
    state: present
    update_cache: yes

- name: Install Zookeeper Repository
  yum:
    name: "https://archive.cloudera.com/cdh5/one-click-install/redhat/{{ansible_distribution_major_version}}/x86_64/cloudera-cdh-5-0.x86_64.rpm"
    state: present
    update_cache: yes

- name: Install Zookeeper package
  yum:
    name: zookeeper-server
    state: latest
    update_cache: yes
  register: zookeeper_install

- name: Initialice zookeeper configuration
  command: service zookeeper-server init
  when: zookeeper_install.changed

- name: Start zookeeper service
  service:
    name: "zookeeper-server"
    state: "started"
