---
- name: Converge
  hosts: all
  become: true
  tasks:

    - name: fix java issue in Ubuntu
      command: mkdir -p /usr/share/man/man1

    - name: "Include grycap.zookeeper"
      include_role:
        name: "ansible-role-zookeeper"
      vars:
        server_list: ["127.0.0.1"]
